"""City & County DIT professional-service category taxonomy.

The annual *Notice to Providers of Professional Services* lists the Department of
Information Technology (DIT) service categories as a lettered ``a.``–``aa.`` list.
That list is:

* the **classification target** for Section I skills (which FY letter a skill is),
  and
* the **source of truth** for correcting stale ``DIT #`` letters carried over from
  an older notice (categories get inserted/removed year to year, so letters drift).

This module parses that lettered list out of the notice PDF with ``pdfplumber``
(already a dependency) and caches it as YAML under ``assets/defaults/`` so the rest
of the app reads a small structured file instead of re-parsing a 20-page PDF every
run. Regenerate with ``python -m proposal.dit_taxonomy [notice.pdf]``.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

from . import config

CACHE_PATH = config.ROOT / "assets" / "defaults" / "dit_taxonomy_fy2027.yaml"

# The DIT department header. Tolerant of the notice's own typo ("TECHNOLOCY") and
# of casing, since the exact wording drifts between years.
_DIT_HEADER = re.compile(r"DEPARTMENT OF INFORMATION TECHNOL", re.I)
# A lettered entry: single/double letter label + ". " + text. The notice letters
# these A.-aa. (FY2027 uppercase, FY2026 lowercase); departments are Roman numerals
# and sub-headers are digits, so a letter label is unambiguous. Case is normalized
# to lowercase to match the firm's "DIT #" column.
_ENTRY = re.compile(r"^([A-Za-z]{1,2})\.\s+(.*\S)\s*$")
_END = re.compile(r"SUBMITTAL REQUIREMENTS", re.I)
# Bare page markers ("12", "-13-") interleave the list at page breaks; skip them.
_PAGE_MARKER = re.compile(r"^-?\d{1,3}-?$")

# Generic words that carry no discriminative signal for keyword matching.
_STOP = {
    "and", "the", "of", "for", "or", "a", "an", "to", "in", "with", "including",
    "services", "service", "support", "design", "development", "management",
    "please", "specify", "area", "expertise", "other", "not", "listed", "above",
    "system", "systems", "including", "related", "software",
}


def _letter_at(index: int) -> str:
    """0 -> 'a', 25 -> 'z', 26 -> 'aa' (spreadsheet-style, lowercase)."""
    s = ""
    n = index + 1
    while n > 0:
        n, r = divmod(n - 1, 26)
        s = chr(97 + r) + s
    return s


def _keywords(name: str) -> list[str]:
    """Significant lowercase tokens from a category name (for fuzzy matching)."""
    out: list[str] = []
    seen: set[str] = set()
    for tok in re.findall(r"[A-Za-z0-9+#.]{2,}", name.lower()):
        tok = tok.strip(".")
        if tok and tok not in _STOP and tok not in seen:
            seen.add(tok)
            out.append(tok)
    return out


def parse_taxonomy(pdf_path) -> list[dict]:
    """Parse the DIT lettered category list from a notice PDF.

    Returns ``[{"letter", "name", "keywords"}]`` in document order. Raises
    ``ValueError`` if the DIT section or a plausible list can't be found.
    """
    import pdfplumber

    with pdfplumber.open(str(pdf_path)) as pdf:
        text = "\n".join((pg.extract_text() or "") for pg in pdf.pages)
    lines = text.splitlines()

    start = next((i for i, ln in enumerate(lines) if _DIT_HEADER.search(ln)), None)
    if start is None:
        raise ValueError("DIT section header not found in notice PDF")

    entries: list[dict] = []
    cur: dict | None = None
    for line in lines[start + 1:]:
        s = line.strip()
        if not s or _PAGE_MARKER.match(s):
            continue
        if _END.search(s):
            break
        m = _ENTRY.match(s)
        # Accept an entry only if its letter is the next expected in sequence,
        # so a wrapped continuation line that happens to start "X. ..." can't
        # be mistaken for a new entry. The next index counts the in-progress entry.
        expected = _letter_at(len(entries) + (1 if cur is not None else 0))
        if m and m.group(1).lower() == expected:
            if cur:
                entries.append(cur)
            cur = {"letter": m.group(1).lower(), "name": m.group(2)}
        elif cur is not None:
            cur["name"] += " " + s
    if cur:
        entries.append(cur)

    if len(entries) < 5:
        raise ValueError(
            f"Only parsed {len(entries)} DIT categories — the notice layout may have "
            "changed; check the PDF and this parser.")

    for e in entries:
        e["name"] = re.sub(r"\s+", " ", e["name"]).strip()
        e["keywords"] = _keywords(e["name"])
    return entries


def _dump(entries: list[dict], fiscal_year: int | None, source: str) -> str:
    header = (
        "# DIT professional-service category taxonomy — generated by "
        "proposal.dit_taxonomy.\n"
        f"# Source: {source}\n"
        "# Regenerate: python -m proposal.dit_taxonomy [notice.pdf]\n"
    )
    body = yaml.safe_dump(
        {"fiscal_year": fiscal_year, "categories": entries},
        sort_keys=False, allow_unicode=True, width=100)
    return header + body


def build_cache(pdf_path=None, *, cfg: dict | None = None) -> list[dict]:
    """Parse the notice PDF and (re)write the YAML cache. Returns the categories."""
    cfg = cfg or config.load_config()
    pdf = Path(pdf_path) if pdf_path else config.notice_pdf_abspath(cfg)
    if not pdf.exists():
        raise FileNotFoundError(f"Notice PDF not found: {pdf}")
    entries = parse_taxonomy(pdf)
    fy = None
    m = re.search(r"(20\d\d)", pdf.name)
    if m:
        fy = int(m.group(1))
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(_dump(entries, fy, pdf.name), encoding="utf-8")
    return entries


def load_taxonomy(cfg: dict | None = None, *, rebuild: bool = False) -> list[dict]:
    """Return the cached taxonomy, parsing the notice PDF on first use / rebuild.

    Falls back to an empty list only if neither a cache nor a parseable notice PDF
    is available (the caller decides how to degrade).
    """
    if not rebuild and CACHE_PATH.exists():
        data = yaml.safe_load(CACHE_PATH.read_text(encoding="utf-8")) or {}
        cats = data.get("categories") or []
        if cats:
            return cats
    try:
        return build_cache(cfg=cfg)
    except (FileNotFoundError, ValueError, ImportError):
        return []


def by_letter(taxonomy: list[dict]) -> dict[str, dict]:
    return {c["letter"]: c for c in taxonomy}


def main(argv=None) -> int:
    import sys
    argv = sys.argv[1:] if argv is None else argv
    pdf = argv[0] if argv else None
    entries = build_cache(pdf)
    print(f"Wrote {CACHE_PATH} ({len(entries)} categories).")
    for e in entries:
        print(f"  {e['letter']:>2}. {e['name'][:70]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
